version: '3'

services:
  mage-ai:
    image: mageai/mageai:latest
    ports:
      - "6789:6789"
    volumes:
      - type: bind
        source: C:\Users\user\Documents\COMESA
        target: /home/src/default_repo/rap
    networks:
      - mage-ai-network

  postgres:
    image: ricardohsmello/postgres-grafana
    container_name: my-postgres
    environment:
      POSTGRES_DB: grafana_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mage-ai-network
      
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - mage-ai-network

  grafana:
    image: grafana/grafana:latest
    container_name: my-grafana
    ports: 
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - mage-ai-network
      
  jupyter:
    build: .
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: C:\Users\user\Documents\COMESA
        target: /home/jovyan/rap
    command: start-notebook.sh --NotebookApp.token=''  # Use empty quotes for no token
    networks:
      - mage-ai-network

volumes:
  postgres_data:
  grafana_data:
  mage-ai-data:
    driver: local

networks:
  mage-ai-network:
    driver: bridge